# Site settings
title: "Bluewind8791 Resume"
description: "Welcome to Kyung-Bin Kim's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kyung-Bin Kim"
resume_title:                   "Resume Title"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "bluewind@kakao.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-6430-8791"
resume_contact_address:         "서울 노원구 한글비석로14길 8"

resume_header_contact_info:     "서울 노원구 한글비석로14길 8 • 010-6430-8791 • bluewind@kakao.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>무역사무원에서 개발자로! 제2의 인생을 꿈꾸며 준비하는 신입 개발자입니다. '스마트팜 개발자 과정'을 통하여 C Language, Python, My-SQL, Network의 기본지식을 배웠고, 현재는 Back-End 개발자 취직을 목표로 Java와 Spring 공부를 하고있습니다!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bluewind8791"
  # resume_twitter_url:           "insert Twitter URL here"
  # resume_dribbble_url:          "insert Dribbble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "insert linkedin URL here"
  # resume_instagram_url:         "insert Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
